<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_About us_vjs-poster</name>
   <tag></tag>
   <elementGuidId>bab90872-69a9-434a-bbd7-666505e4d5dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.vjs-poster</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='example-video']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.vjs-poster</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5985d5f-cef7-413c-88b3-618bd4e78419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-poster</value>
      <webElementGuid>6ba68411-b326-4f5d-8bdd-e1fa0a69a0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b97c31ea-8c5c-49de-8043-e2b597477979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d402067-0c6f-4487-a3c4-bb29ff19e3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example-video&quot;)/div[@class=&quot;vjs-poster&quot;]</value>
      <webElementGuid>95ca6c7a-d019-4fb5-9f49-9c009f13a68e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='example-video']/div</value>
      <webElementGuid>8d1c917e-f191-4cf4-a120-c3dc5e966698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>b1612b1a-c93a-44f3-a336-c2b1167cc34f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
