<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Previous_carousel-control-next-icon</name>
   <tag></tag>
   <elementGuidId>6b18bbfa-8687-4001-b602-e6187aefbb0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.carousel-control-next-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselExampleIndicators']/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#carouselExampleIndicators >> internal:role=button[name=&quot;Next&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>102701ae-022f-4b5f-a88b-5b502d192eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-next-icon</value>
      <webElementGuid>db287f6c-8013-410e-84a1-4ed3e4ff8517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb12e8ef-3720-44f7-9e0b-2543481a58c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselExampleIndicators&quot;)/a[@class=&quot;carousel-control-next&quot;]/span[@class=&quot;carousel-control-next-icon&quot;]</value>
      <webElementGuid>f13a408b-3607-4d93-a858-f6e84568aa31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselExampleIndicators']/a[2]/span</value>
      <webElementGuid>0d65b642-0376-4851-b572-47d61bccef7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>a2b8ad9a-27e1-4060-8b8f-fcbaa0d96659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
